# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('track', models.CharField(max_length=200)),
                ('main_branch', models.CharField(max_length=200)),
                ('personal_background', models.CharField(max_length=2000)),
                ('join_date', models.DateTimeField()),
            ],
        ),
    ]
