# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scsite', '0002_auto_20170622_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80)),
                ('stNumber', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('city', models.CharField(max_length=40)),
                ('postalCode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('country', models.CharField(default='ישראל', editable=False, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=80)),
                ('activityTimes', models.CharField(max_length=80)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scsite.Address')),
            ],
            options={
                'ordering': ('branchName',),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackName', models.CharField(max_length=80)),
                ('branch', models.ManyToManyField(to='scsite.Branch')),
            ],
            options={
                'ordering': ('trackName',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='main_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scsite.Branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scsite.Track'),
        ),
    ]
