# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scsite', '0003_auto_20170622_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='availableTracks',
            field=models.ManyToManyField(to='scsite.Track'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='activityTimes',
            field=models.CharField(default='למשל, ימי שני 19:30-22:00', max_length=80),
        ),
    ]
